# Test $d

name: Test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Run
      run: |
        perl piFromPrimes.pl 1e2
        perl piFromPrimes.pl 1e3
        perl piFromPrimes.pl 1e4
        perl piFromPrimes.pl 1e5
        perl piFromPrimes.pl 1e6
        perl piFromPrimes.pl 1e7
